### ISSUE TITLE
Decrypt and encrypt do not work correctly

### ISSUE THREAD

**Issue by OK2MOP** [amoxu/Baofeng-UV-5RM-5RH-RE#4]
Hello, there is an issue with the .c files for encrypting and decrypting the firmware, as an (signed) char is compared with 0xff which means that the 0xFFs are decrypted/encrypted by mistake. 

Also I do not see a firmware splitter, which would extract the two parts before encryption and decryption reading the 16-byte header in the beginning of the file (0x02 P1_length(unsigned int), P2_length(unsigned int), 7 random bytes) and extract first part from offset 16 and second part from 16+P1_length.

I have made a Python script to extract/combine the firmware, but cannot attach it here.

**Comment by amoxu** [comment]
Hi,
the commit 3f1b82558e8e5a7dc79ad235cff1f2f73fcfeb0d fixed signed char type issue, thank you very much!

For the tool for wrapping/unwrapping, it had been committed by 72f71b6a8de1d35a2b3a3073c88eba2a6e9b02ba .
For the document of wrap tool ,refer to https://github.com/amoxu/Baofeng-UV-5RM-5RH-RE/tree/main/reverse_engineering/uv5rm-wrap-tool

**Comment by amoxu** [comment]
btw, your pr also had been merged, thank you very much.
